### ISSUE TITLE
CyVerse Atmosphere access reference

### ISSUE THREAD

**Issue by unode** [datacarpentry/cloud-genomics#21]
Currently in order to gain access to Atmosphere through CyVerse you are required to reference a Sponsor or Instructor. I would like to work on this material but as it's not part of training I don't have a name and email to reference. Are there any common practices on this front?

As a side-note, current materials warn that a .edu/.org email is required. This does not seem to be the case anymore. I used an institutional email that does not use these Top Level Domain.

**Comment by ACharbonneau** [comment]
I confess, I don't know anything about CyVerse. @JasonJWilliamsNY wrote all the CyVerse material, and might know about the sponsor/instructor question...

**Comment by JasonJWilliamsNY** [comment]
I can be assigned iPlant (Now CyVerse) content. This should be assigned to me for launching your own instance. Will be helpful if the relevant maintainer reached out and I can do a PR

**Comment by ACharbonneau** [comment]
@JasonJWilliamsNY Hi! This was backburnered as it was unclear whether we want to actually maintain CyVerse material. The most recent decision was to make all content except for logging into a pre-started instance an "on your own" activity rather than part of the lesson. Those parts of the lesson are also not being actively updated at this point, as we were deciding whether to keep them at all. If I get word that DC wants us to actively maintain them, I'll poke you.
