### ISSUE TITLE
Reference image and out of cloud capabilities

### ISSUE THREAD

**Issue by unode** [datacarpentry/cloud-genomics#23]
The two platforms currently mentioned in the lesson have their own reference images. From the guidelines it seems the images are maintained independently and are not original to the lesson.

As far as I could gather most cloud platforms require a somewhat specific image configuration. I couldn't find an easy way to download an image for local testing or transfer to a different cloud provider.

* With that in mind, is there any reference of the minimal software (and versions) that should be present in an image for full compatibility with the lesson?

On another point, as access to the cloud platforms mentioned may be take some time (I'm still waiting on CyVerse access approval):

* Would it make sense to have a reference image available in a system that is independent from the cloud platform? [Singularity](http://singularity.lbl.gov/) or [Docker](https://www.docker.com/) come to mind. 

This could facilitate local testing of any step of the lesson and offline/after-workshop reviews. Even if running the full analysis may be too much for a laptop/desktop computer, it may be possible to review and test some of the steps with a smaller dataset or a subset of the data.

**Comment by ACharbonneau** [comment]
Sorry it's taken a while to get to this. We're dropping everything except AWS instructions for this release. Similarly, the 'your own instance' stuff is no longer part of the workshop (exactly because it can take forever to be granted access), however, we're going to maintain the instructions for learners that want to come back after the workshop. 

Given that, I doubt we want to maintain reference images for non-AWS services, but we could use some better non-AWS instructions at https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/06-launching-your-own-instance.md
