### ISSUE TITLE
Possible text for the CITATION

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [datacarpentry/cloud-genomics#3]
Because I usually create a working branch of SWC/DC/LC code
that I can render as a fully offline capable resource, so one that
doesn't require a server to view the local HTML, and can just be
navigated with file:///path/to/  URIs, I'm aware, having just created
such a branch that the current Lesson template's CITATION text
is

'''
Please cite as:

Greg Wilson (ed.): "Software Carpentry: Lesson Example."  Version
2016.06, June 2016, https://github.com/swcarpentry/lesson-example,
10.5281/zenodo.58153.
'''

and so ours might be of the form

'''
 Please cite as:
 
 Some Body (ed.):
 "Data Carpentry Cloud Genomics Lesson"
Version ?.?, Jul 2017, https://github.com/datacarpentry/cloud-genomics
DOI pending.
'''
so thought to suggest that as a prototype, rather than the existing `FIXME` text

**Comment by ACharbonneau** [comment]
Seems like a good idea to me.

**Comment by thomcuddihy** [comment]
Is this still outstanding?

**Comment by ACharbonneau** [comment]
I think so.

**Comment by thomcuddihy** [comment]
Just not sure where this is, sorry..

**Comment by pawsey-kbuckley** [comment]
Re  @thomcuddihy's comment back in April.

Apologies for not getting back to you/this thread/ (I moved jobs and countries)

At the bottom of a Carpentry page, there is a Cite link in the "footer menu".

**Comment by pawsey-kbuckley** [comment]
Typically, if you use the standard lesson-template, that link takes you back 
to a blob in the GitHub repo, that, whilst containing the text of the citation
that you'ld like to present to the reader, isn't much use (read: becomes a
/broken line/link to nowhere/ if you are not on-line).

However, because that blob in the GitHub repo gets distributed when you
download/clone  the lesson sources, you should really be turning it into a
"local to the lesson" HTML file, just like all the other lesson content.

This issue (also still open and still seemingly awaiting discussion in the
higher echelons of Carpentry-land) 

https://github.com/carpentries/lesson-example/issues/142

explains things from the lesson template side of things.

Hope that's a bit clearer and/or allows you to close this issue,
not least as, if, when one is on-line, one clicks on the Cite button
in the footer menu at present, you get taken to some "citation" text .

Clearly, if the lesson template change gets applied, and this lesson
then rebases itsef using that altered template, that citation text will
be rendered as a local file (as, I'd venture, it really should be)

**Comment by tracykteal** [comment]
Thanks for revisiting this. So, the Citation file is now up to date, but the issue is that it links to a URL, rather than a locally referenced file, which it could since it is local, and would be nice if you have a local clone. I'll comment on the lesson-example issue you reference. We could still make the change here in _includes/lesson_footer.html as a proof of concept.
