### ISSUE TITLE
cloud lesson at the beginning or end of workshop

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/cloud-genomics#35]
It came up in the discussion on the 'genomics-workshop' page about where we teach the cloud lesson. I've been teaching it at the beginning when we have people log into the cloud.

From the discussion though, I see the point that it might make more sense to teach it at the end. In the shell lesson, we could have the 'connecting to the cloud' piece. e.g. https://github.com/datacarpentry/shell-genomics/issues/106

Then they could go through the workshop, and at the end, have a "How to Use Cloud Resources" lesson, which goes through how to transfer data to/from the cloud, and what some of the options are.

Having it at the end might also make it an easier integration with people teaching on HPC/HTC. The HPC folks could have the "logging into the HPC" at the beginning with the shell lesson and do things interactive. Then at the end, they could use this time to teach people how to write qsub scripts and submit jobs on their HPC. 

What do people think?

**Comment by ACharbonneau** [comment]
I've also always taught it at the beginning, but @ErinBecker makes a good argument for it being last. 

I suspect that which is 'best' might be dependent on the learner level: I would be annoyed/frustrated that the workshop essentially starts with having me do an important but largely un-explained cloud log-on, and other more experienced learners might be as well. 
But learners who come with no background will likely get much more out of the cloud being at the end, where they now have a context for it.

🤷‍♀️

**Comment by tracykteal** [comment]
Right, for people new to the concept of the command line, it does sound like introducing it without all the information on cloud computing is less cognitive overhead. I think we'll need to be sure to add something to the shell lesson that at least explains that we'll be connecting to a remote computer and generally what that is. So, moving cloud to the end, does really need to go hand and hand with something like https://github.com/datacarpentry/shell-genomics/issues/106

**Comment by tracykteal** [comment]
Even with the cloud at the end though, I don't think we can include how they can spin up their own Amazon instances. To do this requires that people have an Amazon AWS account and a credit card attached to that account. So sign up can take a while, and some people might not even have or want to use a credit card. So, that lesson would still need to focus on conceptual ideas of the cloud, and then can point towards the resources they would need to figure out how to spin up their own instances.

**Comment by ACharbonneau** [comment]
My understanding from the meeting yesterday was that people put it at the end as a "now that you understand all this, this is how you get back here", so it was explicitly about getting an AWS instance and reconnecting to the DC dataset, with some extras about eventually using AWS for your own data. Then we would eventually add a generalized 'how to connect to an hpc' and possibly other platforms.

It sounds like you're suggesting something more like just the current first page of the lesson? https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/01-why-cloud-computing.md  ?

**Comment by tracykteal** [comment]
Thanks for that clarification. No, I think something just like that first page of the lesson is good. I just wanted to make sure the plan for the lesson wasn't having people spin up their own instance. I think we're on the same page!

**Comment by ACharbonneau** [comment]
I'm not sure, but I think we're talking about two different lesson plans...

My understanding from the meeting was that what the instructors wanted was "now that you understand all this, this is how you get back here", as in:

- How to launch a *brand new* EC2 instance 
- How to connect that instance to the DC volume, so interested students can run through the tutorial on their own after the workshop is over and the class instance is killed
- Some supplementary stuff about what to consider when launching an EC2 for your own data

This would require both a credit card and a AWS account for each student.

I think what you mean is "now that you understand all this, this is how you get back here", as in:
- Students closing out their connections to the classroom instance
- Students re-connecting to that same classroom instance
- Some supplementary stuff about what to consider when launching an EC2 for your own data

Now that I've written it out, I can see how the first one is untenable, because the entire lesson would be consumed with getting accounts set up. 

However, I don't see how the second option is different from the 'how to connect' bit at the beginning of the workshop. 

Were you thinking that the cloud lesson, is *just* the first page we currently have? Something else?

**Comment by tracykteal** [comment]
Right, the first version isn't practical because of the issue with setting up accounts.

So, I am more thinking of the second version. It is mainly the page we have already, but it could be expanded. Right now we just say "the instructions for how to set up your own instance are here. You can look at them later." Even without having them spin up their own instance, we can walk through it a bit. People always have questions, and it would be a good time to answer them. 

We can also be sure to show how to transfer data to/from the instances. This is really important for people using cloud resources. This was maybe covered in one of the other lessons, but I'm not sure where or how extensively. So, this lesson would be a good place to cover that. It also would be a reasonable transition from "now you've just run this bioinformatics pipeline and generated your data. Now how do you get the output files back on your computer."

In general there is some trepidation at the end of this workshop about how they'll do it on their own with their own data, so this is an opportunity to pro-actively answer some of those questions and give some time for questions. 

Does that kind of a lesson seem like it would be reasonable here?

**Comment by ACharbonneau** [comment]
We actually have the data moving bit, so that can stay. 

So, just to get this in a list before I forget, we can re-arrange to:

1. Why clouds are good for computing, which you should understand now
2. You logged off the instance for lunch/break, let's review of back on a running instance 
   - this page also has a link to "how to start an instance" that isn't part of the lesson per se and is just AWS instructions for now
3. Let's pretend this is an instance you started, what are some commands you can do to verify it
4. Let's pretend this is an instance you started, how do you move data back and forth 
5. We're almost done! Let's make sure you're ready
   - What to consider when choosing your cloud resource. This might be a good thought exercise rather than lecture. Have them come up with scenarios that apply to their work, and then try to suggest options that fit those scenarios. We could even have a pre-fab table of what resources are good at which things so the instructor doesn't have to wing it.
   - What else are you unsure of?

**Comment by tracykteal** [comment]
That's great! 

I like the pre-fab table of resources too. Probably most instructors are aware of some resources but not others. And it will be really useful to the learners after the workshop.

**Comment by tracykteal** [comment]
I should be able to work on that table next week.

**Comment by ACharbonneau** [comment]
Re-org done. Still need table and/or info filled in for https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/05-which-cloud.md

Going to make this its own issue with the right title.
