### ISSUE TITLE
Info in scp section of data roundtripping is redundant with wrangling

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/cloud-genomics#50]

**Comment by ACharbonneau** [comment]
So. I think it's actually good to come back to scp here, since round-tripping is entirely about moving data, whereas in wrangling its it's being used to get through the lesson. Also, in round-tripping we're covering it a little more, and can move files back and forth as an exercise, which would be a distraction in wrangling.

What do you think about wrangling dropping some of the explanation about scp, and editing the cloud part to acknowledge that they've seen it before, but now we'll explain it, rather like we did with ssh?

**Comment by tracykteal** [comment]
It's good to have each module be standalone, especially since we'll be adding modules or updating for HPC, so I think redundancy is OK. We could put a note in here that they may have seen this before. Then if it was already covered in wrangling, the instructor wouldn't need to cover it again.

**Comment by ErinBecker** [comment]
Marking this for the next release so we remember to add a note that this was covered previously.
