### ISSUE TITLE
AWS instance: dcuser not in the sudoers file

### ISSUE THREAD

**Issue by bebatut** [datacarpentry/cloud-genomics#65]
Hi,

I am using a AWS instance to run this session. 
On my instance, `dcuser` is not in the sudoers file. So I could not run any `sudo` command, particularly the `apt-get` from the tutorial.
How can we to fix that?

Bérénice

**Comment by ErinBecker** [comment]
Pinging @fmichonneau for guidance.

**Comment by ErinBecker** [comment]
See bottom of https://github.com/datacarpentry/cloud-genomics/issues/49

**Comment by ACharbonneau** [comment]
Yes. I had the same problem at my last workshop. We talked about it at the maintainers meeting a couple weeks ago but didn't come up with a fix.

**Comment by fmichonneau** [comment]
I wasn't part of the initial set up for the image but I think remembering that it was by design that users were not able to install software on the instances. @JasonJWilliamsNY probably knows more.

**Comment by ACharbonneau** [comment]
I believe the maintainers meeting I was talking about it on was the one where @taylorreiter was describing the plan to overhaul the whole Genomics lesson. Possibly the sudo section is being dropped? Or the image is being changed?

**Comment by taylorreiter** [comment]
For installations, we are now relying on miniconda. `dcuser` still does not have `sudo` privileges so that users can't accidentally delete something like `usr/bin`. 

We should therefore update the section "Installing additional software" in cloud-genomics/_episodes/03-verifying-instance.md to clarify or remove the `sudo` parts, and potentially add miniconda. Thoughts on this?

As a side note, if you would like to use the AMI associated with the DC genomics lessons separate from these lessons , you could log in as `ubuntu@ipaddress`. You can only do this if you started the instance from your own AWS account and have the key file associated with it on your computer.

**Comment by ACharbonneau** [comment]
@JasonJWilliamsNY @ErinBecker 
In a maintainer meeting some time ago we discussed getting rid of the apt-get section, because it requires sudo, and we don’t give users sudo access
But the apt-get section didn’t get dropped for some reason when Taylor et. al did the big overhaul
I’ve just checked and it still doesn’t work…do you know if it was kept with the intention of updating permissions so users can do it? Or does it still need to be taken out?

**Comment by ACharbonneau** [comment]
The question above is for https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/03-verifying-instance.md specifically, where we are showing users how they would download/install software that isn't in their default instance. I think that is valuable information for learners who will go get their own AWS instances, but I don't know how common that is, or it ifs worth any (potential) security issues associated with adding dcuser to the sudoer file. Potential fixes that I've thought of:
- add dcuser to sudoer file, leave lesson as is
- remove all the apt-get stuff, leave instance security as is
- remove the update and install commands, but show users how to search with apt-get, so they have some familiarity with the system, add some pseudo-code into the lesson about how, if they owned the instance, they *could* actually install the thing they found, leave instance security as is
- remove all the apt-get stuff, leave instance security as is, add in conda install instructions- this works with current security settings since conda itself is already installed.

**Comment by ErinBecker** [comment]
Thanks for updating this issue @ACharbonneau and for pinging @JasonJWilliamsNY as a member of the technical maintainers group for this curriculum. My suggestion is @ACharbonneau's 3rd option above.

**Comment by ErinBecker** [comment]
Hey @ACharbonneau - @fmichonneau is getting ready to mint the lesson releases on Zenodo early next week. I know we haven't heard back from @JasonJWilliamsNY on this issue yet, but wondering if we could implement one of the strategies you suggested above to make sure the lesson is fully functional for release. I think for timing sake, we'll need to leave the instance security as is for this release, but any of the last three options on your list sound like they would be fully functional for this version. Is there anything I can do to help get one of those options implemented by say Tuesday next week so we can include this lesson with the other Genomics lessons in the release next week? Sorry for the time pressure - if the timing doesn't work out, I can set up a release for this lesson independently a little bit later on.

**Comment by ACharbonneau** [comment]
I'll try to get to it over the weekend.

**Comment by ErinBecker** [comment]
Very much appreciated @ACharbonneau. Let me know if I can help.

**Comment by ACharbonneau** [comment]
Edited. https://github.com/datacarpentry/cloud-genomics/pull/91

I also don't need that instance anymore. This all should work. :)
