### ISSUE TITLE
Need to edit supplementary materials to remove login info

### ISSUE THREAD

**Issue by ACharbonneau** [datacarpentry/cloud-genomics#78]
https://datacarpentry.org/cloud-genomics/LaunchingInstances/

has data carpentry username and password. If a user wants to launch their own instance but load the preconfigured DC image, I think they might need the log-in info?  I'm not sure if that's a user story we want to support though. 

thoughts?

**Comment by ErinBecker** [comment]
Instructions for users launching their own AWS instances have been moved to [the overall workshop repo](https://datacarpentry.org/genomics-workshop/AMI-setup/index.html). Log-in info has been removed, as users will either be given log-in info by workshop admins or will need to set up their own key pair. However, this means that the instructions are now out of date, as they tell users to select "Proceed without key pair". Closing this issue here and creating a new one in the overall workshop repo.
