### ISSUE TITLE
Write content for setup page

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/cloud-genomics#8]
[Setup](http://www.datacarpentry.org/cloud-genomics/setup/)

What is setup for this section? /if we are covering AWS setup in a separate section, yes?/

**Comment by ACharbonneau** [comment]
Now that we're at the end of the workshop, I don't think we have any setup?

If we don't, can we easily drop Setup from the landing page table? Or do we just replace #FixMe with nothing?

**Comment by ErinBecker** [comment]
@ACharbonneau @dvanic - There have been several issues raised around setup instructions across the different Genomics lessons. Since these issues are deeply inter-connected, I've created a single meta-issue on the genomics-workshop repo and am closing the issues in the individual lessons. This way we can implement a single fix that is consistent across all the lessons.
