### ISSUE TITLE
Huge dataset problem

### ISSUE THREAD

**Issue by ZarulHanifah** [datacarpentry/cloud-genomics#85]
Hello Data Carpentry instructors,

Amazing work! Like all the other tutorials, the cloud-genomics tutorial is well written, so it is easy to understand.

Just wondering, what if one has a very huge dataset requiring ~512 cores, ~1 Tb RAM, something that needs more than one instance? Would you advise learning AWS Batch? Because it seemed like a lot of work to use Batch, and I am not familiar with Dockers. I have worked with HPC scheduler before.

**Comment by dvanic** [comment]
@ZarulSaurus I think the answer is "it depends". If you have access to a University or other in-house HPC cluster, it will probably be most cost-effective for you to use that; see [here](https://datacarpentry.org/cloud-genomics/04-which-cloud/index.html) for more discussion. Otherwise, it's probably mostly a cost balance, as opposed to a technology/platform choice.

Having said that, when moving to cloud, I would advise learning about docker irrespective of which platform you go with because it allows you to set up the same environment on every system.
