### ISSUE TITLE
Transferring data section - move from shell to cloud lesson?

### ISSUE THREAD

**Issue by aschuerch** [datacarpentry/cloud-genomics#87]
There is a section in shell lesson "Transferring Data Between your Local Machine and the Cloud" in https://datacarpentry.org/shell-genomics/05-writing-scripts/ and an issue in the repo which raised the question if this would not better fit in the cloud lesson. See https://github.com/datacarpentry/shell-genomics/issues/207

**Comment by ACharbonneau** [comment]
That actually was originally in the cloud lesson. It got moved to the shell lesson in the last big overhaul. I'm not opposed to having it back, but I think it moved to your section because otherwise we'd have to either: 
- take back the scripting too, or some other lesson that reasonably belongs in the shell so we have something to move around
- have a bit of our lesson that has us moving files back and forth between computers for no reason at all
