### ISSUE TITLE
Introduction - clean up to match objectives, and move material to other sections?

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/cloud-genomics#9]
[Introduction](http://www.datacarpentry.org/cloud-genomics/01a-deprecated-javascript-loop/)

- [ ] Lesson objective says "What is cloud computing?" but this is not covered in the materials. Write this section (short!)
- [ ] Make sure to define what a "remote server" is

Do we need to split this section into the 3 versions (AWS/HPC/CyVerse), or should this one be the same for all 3, and THEN the next section (logging on merged with "Why of Cloud computing") have the split into the 3 options?

**Comment by ACharbonneau** [comment]
I think we want the split further along, at "Logging in"

I also think it would be easier to read the pages if there was a second split for mac/pc/linux

**Comment by dvanic** [comment]
@ACharbonneau Do you know if there is technically a way to split both aws/CyVerse/HPC and mac/pc/linux on the same page? 

Or should we separate the current lessons in such a way that we'd have one split per lesson, i.e. AWS/CyVerse/HPC for one page, and Mac/Win/Linux on another?

**Comment by ACharbonneau** [comment]
I'm honestly not sure how to implement it ATM, but ideally, I'd like to have a page of log-in instructions that only includes the info relevant to the current learner. So, "AWS for PC",  "HPC for Mac", etc. I find that students get really confused by multiple sets of instructions on a single page, especially in the early parts of the lesson.

If we have to have pages with divergent instructions, then I really want to see better delineation between them, and more obvious headers. People get super frustrated when they learn they've spent the last few minutes failing to get the instructions working because they're using PC instructions on a Mac or similar. Especially for these early, first day lessons, I want them to be absolutely trivial to navigate.

**Comment by devbioinfoguy** [comment]
This is what the Javascript can be used for with a pop-up menu, to show the appropriate section and hide the non-relevant ones. But should we do this the simple way: big section titles, TOC at top, etc for now, and then release the Javascript pop-up once completely implemented?
